from django.urls import path
from .views import (
    RadiosondeProcessView,
    RadiosondeHodographImageView,
    RadiosondeHodographView,
    RadiosondeProfileView,
    RadiosondeReportCreateView,
    RadiosondeReportFileView,
    RadiosondeReportStatusView,
    RadiosondeSearchView,
    RadiosondeSkewTImageView,
    RadiosondeSkewTView,
    RadiosondeStabilityView,
    RadiosondeThermodynamicsView,
    RadiosondeWindView,
)

urlpatterns = [
    path('radiosondes/search/', RadiosondeSearchView.as_view(), name='radiosonde-search'),
    path(
        'radiosonde-reports/',
        RadiosondeReportCreateView.as_view(),
        name='radiosonde-report-create',
    ),
    path(
        'radiosonde-reports/<int:report_id>/',
        RadiosondeReportStatusView.as_view(),
        name='radiosonde-report-status',
    ),
    path(
        'radiosonde-reports/<int:report_id>/file/',
        RadiosondeReportFileView.as_view(),
        name='radiosonde-report-file',
    ),
    path(
        'radiosondes/<int:profile_id>/profile/',
        RadiosondeProfileView.as_view(),
        name='radiosonde-profile',
    ),
    path(
        'radiosondes/<int:profile_id>/thermodynamics/',
        RadiosondeThermodynamicsView.as_view(),
        name='radiosonde-thermodynamics',
    ),
    path(
        'radiosondes/<int:profile_id>/stability/',
        RadiosondeStabilityView.as_view(),
        name='radiosonde-stability',
    ),
    path(
        'radiosondes/<int:profile_id>/wind/',
        RadiosondeWindView.as_view(),
        name='radiosonde-wind',
    ),
    path(
        'radiosondes/<int:profile_id>/skew-t/',
        RadiosondeSkewTView.as_view(),
        name='radiosonde-skew-t',
    ),
    path(
        'radiosondes/<int:profile_id>/skew-t/image/',
        RadiosondeSkewTImageView.as_view(),
        name='radiosonde-skew-t-image',
    ),
    path(
        'radiosondes/<int:profile_id>/hodograph/',
        RadiosondeHodographView.as_view(),
        name='radiosonde-hodograph',
    ),
    path(
        'radiosondes/<int:profile_id>/hodograph/image/',
        RadiosondeHodographImageView.as_view(),
        name='radiosonde-hodograph-image',
    ),
    path('process/', RadiosondeProcessView.as_view(), name='radiosonde-process'),
]
