# Generated by Django 6.0.3 on 2026-03-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_first_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='created',
            new_name='CreationDate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='CreationDate',
        ),
        migrations.AddField(
            model_name='persona',
            name='DeleteDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='UpdateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='DeleteDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='UpdateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
