# Generated by Django 6.0.3 on 2026-03-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_created_persona_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
        migrations.AlterModelTable(
            name='rolpersona',
            table='rol_persona',
        ),
        migrations.AlterModelTable(
            name='roluser',
            table='rol_user',
        ),
        migrations.AlterModelTable(
            name='user',
            table='usuarios',
        ),
    ]
