# Generated by Django 6.0.3 on 2026-03-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_persona_table_alter_rolpersona_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
