# Generated by Django 6.0.3 on 2026-03-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_persona_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitacion',
            old_name='created',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='CreationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='DeleteDate',
            new_name='delete_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='CreationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='DeleteDate',
            new_name='delete_date',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='UpdateDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UpdateDate',
        ),
        migrations.AddField(
            model_name='invitacion',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
