# Generated by Django 6.0.3 on 2026-03-12 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_created_invitacion_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invitacion',
            table='invitacion',
        ),
    ]
